import { TrashReport } from '../types/citizen';

export const MOCK_REPORTS: TrashReport[] = [
  {
    id: '1',
    idempotency_key: 'mock_1',
    citizen_id: 'user_1',
    trash_type: 'Organik',
    estimated_weight: 2.5,
    location_lat: -6.2000,
    location_lng: 106.8166,
    accuracy: 12,
    loc_timestamp: Date.now(),
    address: 'Jl. Merdeka No. 1, Surabaya',
    status: 'pending',
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: '2',
    idempotency_key: 'mock_2',
    citizen_id: 'user_1',
    trash_type: 'Anorganik',
    estimated_weight: 5.0,
    location_lat: -6.2100,
    location_lng: 106.8266,
    accuracy: 8,
    loc_timestamp: Date.now(),
    address: 'Pasar Tradisional Wonokromo',
    status: 'scheduled',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: '3',
    idempotency_key: 'mock_3',
    citizen_id: 'user_1',
    trash_type: 'B3',
    estimated_weight: 1.2,
    location_lat: -6.2200,
    location_lng: 106.8366,
    accuracy: 15,
    loc_timestamp: Date.now(),
    address: 'Area Industri Rungkut',
    status: 'completed',
    points_earned: 150,
    created_at: new Date(Date.now() - 172800000).toISOString(),
    updated_at: new Date(Date.now() - 172800000).toISOString(),
  }
];
